// zxh-012/frontend/src/App.vue
<template>
  <div class="min-h-screen bg-gradient-to-br from-amber-50 via-orange-50 to-red-50">
    <header class="bg-white/80 backdrop-blur border-b border-orange-100 sticky top-0 z-50">
      <div class="max-w-7xl mx-auto px-4 py-4 flex items-center justify-between">
        <h1 class="text-2xl font-bold text-orange-800">方言声音档案馆</h1>
        <nav class="flex gap-1">
          <button v-for="tab in tabs" :key="tab.id"
            @click="activeTab = tab.id"
            :class="['px-4 py-2 rounded-lg text-sm font-medium transition',
              activeTab === tab.id
                ? 'bg-orange-600 text-white shadow'
                : 'text-gray-600 hover:bg-orange-100']">
            {{ tab.label }}
          </button>
        </nav>
      </div>
    </header>

    <main class="max-w-7xl mx-auto px-4 py-6">
      <RecordingUpload v-if="activeTab === 'upload'" @uploaded="onUploaded" />
      <RecordingList v-else-if="activeTab === 'browse'" @select="onSelectRecording" />
      <MapView v-else-if="activeTab === 'map'" :recording-id="selectedRecordingId" />
      <GameChallenge v-else-if="activeTab === 'game'" />
      <VocabularyPanel v-if="selectedRecordingId" :recording-id="selectedRecordingId"
        @close="selectedRecordingId = null" />
    </main>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import RecordingUpload from './components/RecordingUpload.vue'
import RecordingList from './components/RecordingList.vue'
import MapView from './components/MapView.vue'
import GameChallenge from './components/GameChallenge.vue'
import VocabularyPanel from './components/VocabularyPanel.vue'

const tabs = [
  { id: 'upload', label: '上传录音' },
  { id: 'browse', label: '浏览录音' },
  { id: 'map', label: '相似度地图' },
  { id: 'game', label: '方言挑战' },
]
const activeTab = ref('browse')
const selectedRecordingId = ref(null)

function onUploaded() {
  activeTab.value = 'browse'
}

function onSelectRecording(id) {
  selectedRecordingId.value = id
}
</script>

// zxh-014/frontend/src/App.svelte
<script>
  import { currentPage, userId } from "./lib/stores.js";
  import Home from "./pages/Home.svelte";
  import Record from "./pages/Record.svelte";
  import Dictionary from "./pages/Dictionary.svelte";
  import Trends from "./pages/Trends.svelte";
  import Community from "./pages/Community.svelte";

  const navItems = [
    { id: "home", label: "首页" },
    { id: "record", label: "记录梦境" },
    { id: "dictionary", label: "符号词典" },
    { id: "trends", label: "趋势分析" },
    { id: "community", label: "匿名社区" },
  ];
</script>

<div class="min-h-screen flex flex-col">
  <nav class="bg-indigo-700 text-white shadow-lg sticky top-0 z-50">
    <div class="max-w-6xl mx-auto px-4 py-3 flex items-center gap-6">
      <span class="text-xl font-bold tracking-wide">梦境符号词典</span>
      <div class="flex gap-1">
        {#each navItems as item}
          <button
            class="px-3 py-1.5 rounded text-sm transition-colors"
            class:bg-indigo-500={$currentPage === item.id}
            class:hover:bg-indigo-600={$currentPage !== item.id}
            on:click={() => currentPage.set(item.id)}
          >
            {item.label}
          </button>
        {/each}
      </div>
      <span class="ml-auto text-xs text-indigo-200">ID: {$userId}</span>
    </div>
  </nav>

  <main class="flex-1 max-w-6xl mx-auto w-full px-4 py-6">
    {#if $currentPage === "home"}
      <Home />
    {:else if $currentPage === "record"}
      <Record />
    {:else if $currentPage === "dictionary"}
      <Dictionary />
    {:else if $currentPage === "trends"}
      <Trends />
    {:else if $currentPage === "community"}
      <Community />
    {/if}
  </main>
</div>
